### ISSUE TITLE
HyperV-Backup-Utility say bkup "Successful" in the object of the email notification even if the bkup failed

### ISSUE THREAD

**Issue by ecomstation** [Digressive/HyperV-Backup-Utility#27] opened 2023-03-12 20:28 UTC
Hi,

latest build
as in the object
even if the bkup fails for e.g. full disk it say "successful" in the subject of the email

email subject:  Hyper-V Backup Utility Log 0/1 VMs Successful

while..
2023-03-12 20:00:05 [INFO] (VM:srv2) Attempting to export VM
2023-03-12 20:00:16 [ERROR] (VM:srv2) Impossibile copiare file durante l'esportazione.
Spazio su disco insufficiente per eseguire la copia in 'c:\bkup\srv2'.
Impossibile copiare i file: Spazio su disco insufficiente. (0x80070070

**Comment by Charles-Isaac** [comment] 2023-06-22 19:42
I have a similar issue

Hyper-V Backup Utility 9/9 VMs Successful
...
2023-06-22 01:00:06 [INFO] Process started
2023-06-22 01:00:06 [INFO] (VM:DependencyGraph) Attempting to export VM
2023-06-22 01:05:48 [INFO] (VM:DependencyGraph) Removing previous backups
2023-06-22 01:05:48 [INFO] Backup directory Z:\(path)\2023-06-22_01-00-04 doesn't exist. Creating it.
2023-06-22 01:09:56 [ERROR] (VM:DependencyGraph) An unexpected network error occurred.
2023-06-22 01:09:56 [SUCCESS] (VM:DependencyGraph) Backup Successful
...

**Comment by furicle** [comment] 2024-04-01 18:53
I can confirm I'm still seeing this on the latest build.
Two examples follow...
One fails for lack of space, the other due to auth issues.  (both were "correct" to fail, there were auth issues and space issues)


`
Subject: Hyper-V Backup Utility Log 2/2 VMs Successful
From: admin@example.com
Date: 4/1/2024, 12:15 AM
To: admin@example.com

--- Running with the following config ---
Utility Version: 24.03.21
Hostname: VSexample.
Windows Version: 10.0.20348.
No. of VMs: 2.
VMs to backup:
dcexample
fsexample
Backup directory: \\backupexample\backup\Server_Backups\Virtual_Server_Backups.
Working directory: C:\Hyper-V_BU\Temp-WorkDir.
Backups to keep: 2 days
Logs directory: C:\Hyper-V_BU\Logs.
E-mail log to: admin@example.com.
E-mail log from: admin@example.com.
SMTP server: Configured
SMTP auth: Configured
---
2024-04-01 00:11:09 [INFO] Process started
2024-04-01 00:11:10 [INFO] (VM:dcexample) has [2] CPU cores, [4GB] RAM, Storage: [Current Size = 26GB - Max Size = 127GB]
2024-04-01 00:11:11 [INFO] (VM:fsexample) has [2] CPU cores, [4GB] RAM, Storage: [Current Size = 102GB - Max Size = 127GB]
2024-04-01 00:11:12 [INFO] (VM:dcexample) Attempting to export VM
2024-04-01 00:12:07 [INFO] (VM:dcexample) Removing backup folders older than: 2 days

dcexample-2024-03-30_00-12-04 3/30/2024 12:11:09 AM


2024-04-01 00:12:08 [INFO] Backup directory \\backupexample\backup\Server_Backups\Virtual_Server_Backups doesn't exist. Creating it.
2024-04-01 00:12:10 [ERROR] (VM:dcexample) The user name or password is incorrect.

2024-04-01 00:12:10 [SUCCESS] (VM:dcexample) Export Successful
2024-04-01 00:12:10 [INFO] (VM:dcexample) Processed in 00:00:58
2024-04-01 00:12:10 [INFO] (VM:fsexample) Attempting to export VM
2024-04-01 00:15:38 [INFO] (VM:fsexample) Removing backup folders older than: 2 days

fsexample-2024-03-30_00-15-34 3/30/2024 12:12:06 AM


2024-04-01 00:15:39 [INFO] Backup directory \\backupexample\backup\Server_Backups\Virtual_Server_Backups doesn't exist. Creating it.
2024-04-01 00:15:41 [ERROR] (VM:fsexample) The user name or password is incorrect.

2024-04-01 00:15:41 [SUCCESS] (VM:fsexample) Export Successful
2024-04-01 00:15:41 [INFO] (VM:fsexample) Processed in 00:03:30
2024-04-01 00:15:41 [INFO] Process finished.
2024-04-01 00:15:41 [INFO] Number of VMs to Backup:2
2024-04-01 00:15:41 [INFO] Backups Successful:2
2024-04-01 00:15:41 [INFO] Backups Failed:0


------------------------------------------------------------------------------------------------------------------------------------------
Subject:
Hyper-V Backup Utility Log 2/2 VMs Successful
From:
admin@muskokaauto.com
Date:
4/1/2024, 4:19 AM
To:
admin@muskokaauto.com

--- Running with the following config ---
Utility Version: 24.03.21
Hostname: VSexample.
Windows Version: 10.0.20348.
No. of VMs: 2.
VMs to backup:
dcexample
fsexample
Backup directory: \\backupexample\backup\Server_Backups\Virtual_Server_Backups.
Working directory: E:\Hyper-V_BU\Temp-WorkDir.
Backups to keep: 2 days
Logs directory: E:\Hyper-V_BU\Logs.
E-mail log to: admin@muskokaauto.com.
E-mail log from: admin@muskokaauto.com.
SMTP server: Configured
SMTP auth: Configured
---
2024-04-01 04:11:02 [INFO] Process started
2024-04-01 04:11:03 [INFO] (VM:dcexample) has [2] CPU cores, [4GB] RAM, Storage: [Current Size = 27GB - Max Size = 127GB]
2024-04-01 04:11:03 [INFO] (VM:fsexample) has [2] CPU cores, [4GB] RAM, Storage: [Current Size = 80GB - Max Size = 256GB]
2024-04-01 04:11:03 [INFO] (VM:dcexample) Attempting to export VM
2024-04-01 04:13:20 [INFO] (VM:dcexample) Removing backup folders older than: 2 days

dcexample-2024-03-30_04-13-11 3/30/2024 4:11:03 AM



dcexample-2024-03-28_04-13-09 3/28/2024 4:13:09 AM


2024-04-01 04:13:21 [ERROR] (VM:dcexample) There is not enough space on the disk.

2024-04-01 04:13:21 [SUCCESS] (VM:dcexample) Export Successful
2024-04-01 04:13:21 [INFO] (VM:dcexample) Processed in 00:02:17
2024-04-01 04:13:21 [INFO] (VM:fsexample) Attempting to export VM
2024-04-01 04:19:26 [INFO] (VM:fsexample) Removing backup folders older than: 2 days

fsexample-2024-03-30_04-19-18 3/30/2024 4:13:11 AM



fsexample-2024-03-28_04-32-54 3/28/2024 4:32:54 AM


2024-04-01 04:19:26 [ERROR] (VM:fsexample) There is not enough space on the disk.

2024-04-01 04:19:26 [SUCCESS] (VM:fsexample) Export Successful
2024-04-01 04:19:26 [INFO] (VM:fsexample) Processed in 00:06:05
2024-04-01 04:19:26 [INFO] Process finished.
2024-04-01 04:19:26 [INFO] Number of VMs to Backup:2
2024-04-01 04:19:26 [INFO] Backups Successful:2
2024-04-01 04:19:26 [INFO] Backups Failed:0

`

**Comment by furicle** [comment] 2024-04-03 22:50
No worries, I feel guilty I haven't had the time to troubleshoot it more!

**Comment by Digressive** [comment] 2024-04-04 14:17
@furicle thats totally ok! troubleshooting takes so much time

**Comment by Digressive** [comment] 2024-05-11 15:02
I believe this is fixed now in Version 24.05.11.

**Closed by Digressive** 2024-05-11 15:02 UTC
Labels: bug
